### PR TITLE
Bump node_js to stable (currently 7) and reorder Travis params

### PR DESCRIPTION
**Pull request by limonte**

### CODE REVIEW

**Comment by limonte** [comment]
any reaction here?

**Comment by notwaldorf** [comment]
Why is this required? Pinging @azakus, who is the kind of our travis config

**Comment by limonte** [comment]
> Why is this required?

This is not required, this is just the bump to latest stable Node.js release so it won't be needed to change the digit in future.

Also small reorganizing and shortening of the `.travis.yml`

**Comment by azakus** [comment]
We're staying on the latest node LTS, which for now is 6.x. This file is also managed by a tool, so it would be better to make a pull request to this file: https://github.com/PolymerLabs/tedium/blob/master/cleanup-passes/travis.ts

**Pull request closed without merging**
