### PR TITLE
Provide standard exports from mock-interactions and test-helpers.

### PR DESCRIPTION
**Pull request by aomarks**
These libraries are now standard ES modules exporting a library of functions. Also converted to more idiomatic ES6 style.

For backwards compatibility, the functions are also still exported to the `MockInteractions` and `TestHelpers` globals, since there are so many existing 3.0 style elements that depend on that usage pattern.

We may want to release a 4.0 version after the 3.0 release that removes these globals.

### CODE REVIEW

**Comment by e111077** [comment]
I agree that this is better, but perhaps we should do what we have done with our styles when we switched from using css mixins to classes: we kept all the old files and added a `classes/` directory. In this case we can probably add an `exports/` dir or something close to that.

My reasoning: a lot of our current tests rely on mock interactions being globally available. It would be quite the effort to go and migrate all of those old repos.

**Comment by aomarks** [comment]
> I agree that this is better, but perhaps we should do what we have done with our styles when we switched from using css mixins to classes: we kept all the old files and added a classes/ directory. In this case we can probably add an exports/ dir or something close to that.
> 
> My reasoning: a lot of our current tests rely on mock interactions being globally available. It would be quite the effort to go and migrate all of those old repos.

At the end of each module, everything is re-exported back to the original global location, so this should cause no incompatibilities, but still allow new code to import in the more standard style.

**Comment by e111077** [comment]
omg I'm dumb I should lern2reed

**Comment by e111077** [comment]
after tests*

**Comment by aomarks** [comment]
> after tests*

Yeah, seems like one of them is just timing out every time after the tests pass.

**Comment by aomarks** [comment]
> Actually I'm paranoid. Can you please make sure this passes an integration test with another element? Probably just fish out an element that requires this package.

Sure, that's a good idea.

**Comment by e111077** [comment]
paper-behaviors has a pretty good suite of tests that uses mock interactions:

https://github.com/PolymerElements/paper-behaviors/tree/3.0-preview-dev

**Comment by notwaldorf** [comment]
All tests on all elements fail on safari rn with a timeout btw.

**Comment by aomarks** [comment]
> paper-behaviors has a pretty good suite of tests that uses mock interactions:
> 
> https://github.com/PolymerElements/paper-behaviors/tree/3.0-preview-dev

Looks good:

```
chrome 68 (102/0/0)                     firefox 61 (102/0/0)                  
safari 11.1.2 (102/0/0)               
```

**Pull request merged**
