### PR TITLE
Added wrapper function for mouseover, mouseenter, and mouseleave

### LINKED ISSUE #65: Add support for mouseover event.
There is no wrapper for mouseover event now.
I think we can reuse makeMouseEvent to come up one wrapper function for mouse over.

### LINKED ISSUE #90: Support for mouseenter and mouseleave events
There's no support for mouseenter and mouseleave events.

### PR DESCRIPTION
**Pull request by QuiWorks**
Fixes #90, fixes #65 by creating three new functions mouseenter(node, xy), mouseleave(node, xy), and mouseover(node, xy) that wrap the makeMouseEvent(eventName, xy, node) function.

### CODE REVIEW

**Comment by QuiWorks** [comment]
I signed it.

**Comment by EricJohnPederson** [comment]
I signed it again.

**Comment by QuiWorks** [comment]
I signed it with the email I made the commits with.

**Comment by EricJohnPederson** [comment]
Hey I'm the same person as QuiWorks just a different account. I don't know how this account got associated with these changes, but I signed the agreement with this account.

**Pull request closed without merging**
