### PR TITLE
Add move() to the MockInteractions scope

### PR DESCRIPTION
**Pull request by limonte**

### CODE REVIEW

**Comment by billy-hardy** [comment]
+1 
I am in need of this as well, if someone could merge.

**Comment by limonte** [comment]
any reaction here?

**Comment by notwaldorf** [comment]
Looks good, thanks

**Comment by limonte** [comment]
For some reason I can't rebase this PR, another one with the same change https://github.com/PolymerElements/iron-test-helpers/pull/74

**Pull request closed without merging**
