### PR TITLE
Add Missing polymer.html Dependency

### PR DESCRIPTION
**Pull request by robliao**
Both mock-interactions.js and test-helpers.js require Polymer.

### CODE REVIEW

**Comment by robliao** [comment]
Ping!

**Comment by robliao** [comment]
Any further action required from me for this PR?

**Comment by cdata** [comment]
@robliao Sorry for the delayed response. Thank you for the contribution.

You are correct that this import is missing. However, I think the best solution for us would be to convert the two JS files into HTML Imports, and include the Polymer dependency in each of them.

Would you be willing to make this change for us?

**Comment by robliao** [comment]
Done. Take a look. Thanks!

**Comment by cdata** [comment]
Thanks @robliao this is great. Now there is an outstanding issue to be resolved before we can merge this: companion PRs must be made against all repos that currently reference the `.js` version of these files. Please stand by while we coordinate this.

**Comment by robliao** [comment]
How's this going thus far? It seems that we can commit these as is, can't we. The JS files aren't going away with this commit.

**Comment by robliao** [comment]
Ping!

**Pull request merged**
